name: jaguar_query_sqljocky
description: MySQL (sqljocky) adapter for jaguar_query and jaguar_orm
version: 2.2.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query:
    path: ../query
  #    git:
  #      url: https://github.com/Jaguar-dart/jaguar_orm.git
  #      ref: 2dc3d243b64bfd497758f18a99bbb651f0528e65
  #      path: query
  sqljocky5:
    path: ../../sqljocky5
  path: ^1.6.2
  type_helper: 0.1.0

dev_dependencies:
  test: ^1.3.0